title: Ayoub ELMOKHTAR
description: Senior Offensive Security Engineering @noon

baseurl:
url: "https://ayoubmokhtar.com"
email: "me@ayoubmokhtar.com"

# Pagination
paginate: 4
permalink: /post/:title/
paginate_path: /research/page:num/

# Social media links in footer
twitter: "aessadek"
linkedin: "aessadek"
github: "aelmokhtar"


# Markdown
markdown: kramdown

# Tracker
google_analytics: G-9H9PVHQFWG


compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
